version: "3.9"
services:
  sensorsmock:
    build: ./sensors
    container_name: sensor
    ports:
      - "3000:3000"
    depends_on:
      - postapi
    environment:
      - SMART_THERMO_BUCKET=capstone-test-1
      - CARBON_SENSE_URL=http://postapi:3001/api/collect/moisturemate_data
      - MOISTURE_MATE_URL=http://postapi:3001/api/collect/carbonsense_data
      - AWS_ACCESS_KEY_ID=ASIAY2K6D3PWCEJQIPOA
      - AWS_SECRET_ACCESS_KEY=YM/E3K3vszCPiXT3RRTNoGNUIMw3lW4hOUqMqLir
      - AWS_SESSION_TOKEN=FwoGZXIvYXdzEOH//////////wEaDBsxwjw9haKsf0tnRCKCAUDRCabbPwn/2aFxueUQotrXOWpHTGEP8TtwmwOClSwzg2dCq4WjbBF6bTJtTmGhyaFoQjysmzXOWYaptg9aJf7DKXL//YnZr83tpoXUMcX+7TLyoSvXB3111CPUqG2QyxaqghpNKjYXc93g0yLTSM3ytWWEEvPoseADKIYZpjBnt/oo+NvPngYyKMOwcVjBr1sOSrMB4tLXLhy1Zm+IYhL18ScxwSRZxUgIpk3quYv5Wls=
  postapi:
    build: ./push-data-handler
    container_name: postapi
    ports:
      - "3001:3001"


