version: "3.9"
services:
  sensorsmock:
    build: ./sensors
    container_name: sensor
    ports:
      - "3000:3000"
    environment:
      - SMART_THERMO_BUCKET=capstone-test-1
      - CARBON_SENSE_URL=http://postapi:3001/api/collect/carbonsense_data
      - MOISTURE_MATE_URL=http://postapi:3001/api/collect/moisturemate_data
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=
  postapi:
    build: ./push_data_handler
    container_name: postapi
    ports:
      - "3001:3001"
  luxdata:
    build: ./lux_microservice
    container_name: getlux
    ports: 
      - "3002:3002"
    environment: 
      - SENSORSMOCK_URL = http://sensorsmock:3000/api/luxmeter      
    depends_on:
      - sensorsmock

  minio:
    image: minio/minio
    restart: always
    command: minio server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY= minioadmin
      - MINIO_SECRET_KEY= minioadmin
    entrypoint: minio server
    command: '/export'

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
      - sensorsmock
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/smartthermo;
      /usr/bin/mc mb myminio/smartthermo;
      /usr/bin/mc policy download myminio/smartthermo;
      exit 0;
      "
