version: "3.9"
services:
  sensorsmock:
    build: .
    ports:
      - "3000:3000"
    volumes:   
      - ./:/app
    environment:
      - SMART_THERMO_BUCKET=capstone-test-1
      - MOISTURE_MATE_URL=http://localhost:3000/api/moisturemate
      - CARBON_SENSE_URL=http://localhost:3000/api/carbonsense
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=
