version: "3.9"
services:
  sensorsmock:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SMART_THERMO_BUCKET=capstone-test-1
      - MOISTURE_MATE_URL=http://localhost:3000/api/moisturemate
      - CARBON_SENSE_URL=http://localhost:3000/api/carbonsense
      - AWS_ACCESS_KEY_ID=ASIAY2K6D3PWCNLNUYVD
      - AWS_SECRET_ACCESS_KEY=zO/81MwjbKh7Yc5T8/9yFXClaBBWmEqelloN7WsJ
      - AWS_SESSION_TOKEN=FwoGZXIvYXdzEIb//////////wEaDILGhQqg1BEf9thkDSKCAZloxfdx6Svgu1tjskJd/jSOAgSGuqcVe53x8AWizo7+h2z2FKvUUVYSjZJsns2JMqSqLVPQi0+D76Ke9lzG7Uth5nyfpxpjo6YBMSwaTXqjIFCa7ZvI5DgtLdDaRvK7LzY7l9kI5dCLtilVk/l1xPz3OOKShd6wiDMjV4/x/VJGnxYo1+q7ngYyKDtFMvyBvKsL/DQolswe5oxyCRgDtAVUDc7WW9PzIUODfOjEy3aKIds=
